### ISSUE TITLE
Riot.im matrix client

### ISSUE THREAD

**Issue by level20peon** [portapps/portapps#10]
> Please follow the following guide to file a proper request report : http://portapps.github.io/doc/request-apps/

* Name : Riot.im
* Description : Open Source Client for the federated Matrix network
* Website : https://about.riot.im/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : OSS (Apache 2.0)
* Comment (anything else which might help) : Seems to use the same packaging structure as Slack, which is already ported. So this could be a simple copy&paste job.

**Comment by crazy-max** [comment]
@level20peon Riot.im portable is now available : https://portapps.io/app/riot-portable/
