### ISSUE TITLE
Notion

### ISSUE THREAD

**Issue by dmipin02** [portapps/portapps#101]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Notion
* Description : Write, plan, collaborate, and get organized. Notion is all you need — in one tool.
* Website : https://www.notion.so/product
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Unknown
* Comment (anything else which might help) :

**Comment by crazy-max** [comment]
I have to contact Notion developers about their licensing strategy before making a portapp.

**Comment by crazy-max** [comment]
@dmipin02 According to their [Terms & Conditions](https://www.notion.so/Terms-Conditions-4e1c5dd3e3de45dfa4a8ed60f1a43da0), it's not allowed to redistribute their product.
