### ISSUE TITLE
Microsoft Edge (Chromium)

### ISSUE THREAD

**Issue by bbley1** [portapps/portapps#102]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Microsoft Edge (Insider/Chromium)
* Description : Edge Web Browser
* Website : https://www.microsoftedgeinsider.com/en-us/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : MIT?
* Comment (anything else which might help) : I dont know about the license information. But if its possible a portable version would be great since Cloud-Syncing does not store our Extension settings & content.

**Comment by ProblematicDude** [comment]
Is the port possible ? . In other duplicate you mentioned, it is Edge(Legacy) but the new EDGE is chromium based which is an open source project. So , Is the port **Possible?**
P.S. - I'm asking for possibility and not ETA.

**Comment by crazy-max** [comment]
According to their Terms of Use, it's not allowed to redistribute their product.

**Comment by Julmik647** [comment]
What's the point? Microsoft Edge is already instaled on most of computers.
