### ISSUE TITLE
TeknoParrot 

### ISSUE THREAD

**Issue by Foxen842** [portapps/portapps#108]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : TeknoParrot
* Description : Arcade Emulator
* Website : https://teknoparrot.com/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Unknown
* Comment (anything else which might help) : 
Right now i notice that it saves settings in the Registry:
[HKEY_CURRENT_USER\Software\TeknoGods]
and in the Appdata Folder.
C:\Users\...\AppData\Roaming\TeknoParrot

**Comment by crazy-max** [comment]
Sorry but based on [Alexa rank](https://www.alexa.com/siteinfo/teknoparrot.com) this application does not have sufficient visibility and trust reputation.
