### ISSUE TITLE
Enhancement: Please add checksum/hash to releases

### ISSUE THREAD

**Issue by snow8gaia** [portapps/portapps#11]
Sometimes, somehow downloads may even lead to subtly corrupted downloads. Any of the hashes would give a better way to verify download completion, i.e., uncover corrupted ones.

Just create the hash after the app is built and publish it alongside the main product(s) on the GitHub release page. 

For example, the appropriate checksum files for the manjaro-xfce-0.8.1-x86_64.iso file (64 bit Manjaro release 0.8.1 with the XFCE desktop) would be: 
manjaro-xfce-0.8.1-x86_64-sha1.sum, and/or 
manjaro-xfce-0.8.1-x86_64-sha256.sum

This would also help in case of users using scripts. Or in cases of unreliable network/connections.

**Comment by crazy-max** [comment]
It is implemented and will be available for future releases. You can find an example [here](https://github.com/portapps/hostsman-portable/releases/tag/4.8.106-9).

**Comment by snow8gaia** [comment]
Thanks for https://github.com/portapps/docker-toolbox-portable/releases/tag/18.09.3-4 

----
figured it out.

```Powershell
> cat checksums.txt | grep 'docker-toolbox-portable-win64-18.09.3-4'
a7e04edca16e017116057420bf67b7bc8d9a0b1e2d5278dbcb9b2dd566ce90db  docker-toolbox-portable-win64-18.09.3-4-setup.exe
056482c446712ef7cfdc00d9a91b6c35e47a5eb8e9d01cbf4eeb9f6915132c10  docker-toolbox-portable-win64-18.09.3-4.7z
> sha256sum.exe 'docker-toolbox-portable-win64-18.09.3-4.7z' 'docker-toolbox-portable-win64-18.09.3-4-setup.exe'
056482c446712ef7cfdc00d9a91b6c35e47a5eb8e9d01cbf4eeb9f6915132c10 *docker-toolbox-portable-win64-18.09.3-4.7z
a7e04edca16e017116057420bf67b7bc8d9a0b1e2d5278dbcb9b2dd566ce90db *docker-toolbox-portable-win64-18.09.3-4-setup.exe
> sha1sum.exe 'docker-toolbox-portable-win64-18.09.3-4.7z' 'docker-toolbox-portable-win64-18.09.3-4-setup.exe'
4863b3556b2b605dc4d87c6a7dce285c4ad807dd *docker-toolbox-portable-win64-18.09.3-4.7z
d197b7d909f2cadf29a5b14f21671ca10137d1f7 *docker-toolbox-portable-win64-18.09.3-4-setup.exe
```
