### ISSUE TITLE
Atom editor

### ISSUE THREAD

**Issue by F3000** [portapps/portapps#113]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Atom
* Description : 
* Website : atom.io
* License (e.g. Freeware, OSS, GPL, MIT, etc) : 
* Comment (anything else which might help) :

**Comment by crazy-max** [comment]
Accodring to their [TOS](https://help.github.com/en/github/site-policy/github-terms-of-service), it's not allowed to redistribute their software.
