### ISSUE TITLE
GitHub Desktop

### ISSUE THREAD

**Issue by xmha97** [portapps/portapps#116]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : GitHub Desktop
* Description : Focus on what matters instead of fighting with Git. Whether you're new to Git or a seasoned user, GitHub Desktop simplifies your development workflow.
* Website : https://desktop.github.com/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : MIT
* Comment (anything else which might help) : GitHub Desktop doesn't support multiple accounts, so I requested a portable version.

**Comment by crazy-max** [comment]
@xmha97 Please search for existing issues before opening a new one. Duplicated of #87

**Comment by xmha97** [comment]
OK, Thank you for your reply 🙏
