### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by xmha97** [portapps/portapps#118]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Spotify
* Description : Spotify is a digital music service that gives you access to millions of songs.
* Website : https://www.spotify.com/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : I don't know
* Comment (anything else which might help) :

**Comment by crazy-max** [comment]
According to their [EULA](https://www.spotify.com/legal/end-user-agreement/), it's not allowed to redistribute their product.
