### ISSUE TITLE
Add settings file

### ISSUE THREAD

**Issue by sXNA** [portapps/portapps#12]
Hi, it is possible to  add support for INI files. Some apps (e.g. browsers) have command line switches. 
Using shortcut or 3rd-party launcher is sometimes not a preferable solution.

The INI file could have structure:

```
[NameOfApp]
EnableCommandLineSwitches=true
CommandLineSwitches=some switches
```

and maybe some other options for portapps wrapper .

**Comment by crazy-max** [comment]
Hi @sXNA, I have already started working on it and you can get a preview with [docker-toolbox-portable](https://portapps.github.io/app/docker-toolbox-portable/) (see _Configuration file_ section) that generates a config file at startup. But I think I'm going to start with a YAML file type that is more user friendly.

**Comment by crazy-max** [comment]
@sXNA This feature has been implemented. See the [Configuration page](https://portapps.github.io/doc/configuration/) for more info.
