### ISSUE TITLE
Jaxx Liberty

### ISSUE THREAD

**Issue by ricardo6nunes** [portapps/portapps#121]
* Name : Jaxx Liberty
* Description : Jaxx Liberty is a cryptocurrency wallet. With features including cryptocurrency portfolio, exchange, markets, news and rewards all in the same app, it's a one-stop gateway to manage your wealth.
* Website : https://jaxx.io/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Jaxx is licensed to You on a personal, non-exclusive, non-transferrable, non-assignable, royalty-free, worldwide basis. Notwithstanding the foregoing, Jaxx includes many open-source software libraries that are separately licensed and the license in this agreement does not cover the third-party open-source software that is bundled with Jaxx.
* Comment (anything else which might help) :

**Comment by crazy-max** [comment]
@ricardo6nunes According to their [Terms of Use](https://jaxx.io/legal/intellectual-property), it's not allowed to redistribute their product.
