### ISSUE TITLE
Typora

### ISSUE THREAD

**Issue by F3000** [portapps/portapps#124]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Typora Markdown Editor
* Description : Modern Cross-Plattform Markdown Editor 
* Website : https://typora.io/
* License (e.g. Freeware, OSS, GPL, MIT, etc) :  I cant see it on the website 
* Comment (anything else which might help) :

**Comment by F3000** [comment]
@crazy-max any thoughts of that?

**Comment by crazy-max** [comment]
@F3000 According to their [End User License Agreement](https://support.typora.io/License-Agreement/), it's not allowed to repackage their product on Windows.
