### ISSUE TITLE
Samsung DEX for Windows

### ISSUE THREAD

**Issue by F3000** [portapps/portapps#132]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Samsung DEX

* Description : Arbeiten auf einem großen Bildschirm? Ganz einfach! Verbinde dein Galaxy Note10/Note10+ mit einem kompatiblen Monitor oder Fernsehgerät, um in den Genuss eines großen Bildschirms zu kommen.

* Website : https://www.samsung.com/de/apps/samsung-dex/

* License (e.g. Freeware, OSS, GPL, MIT, etc) : not quoted 
* Comment (anything else which might help) : 

Hopefully it is working

**Comment by crazy-max** [comment]
@F3000 According to their [Terms of Use](https://developer.samsung.com/terms?lang=en), it's not allowed to redistribute their product.
