### ISSUE TITLE
Transmission

### ISSUE THREAD

**Issue by SimonFranc** [portapps/portapps#133]
* Name : Transmission
* Description : BitTorrent client
* Website : https://transmissionbt.com/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : GNU GPLv2 & GNU GPLv3 & Mnemosyne LLC

**Comment by guneethind** [comment]
yeah we want this please

**Comment by crazy-max** [comment]
Available: https://portapps.io/app/transmission-portable/
