### ISSUE TITLE
Roblox

### ISSUE THREAD

**Issue by thuanga83vn** [portapps/portapps#134]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Roblox
* Description : Roblox Portable
* Website : https://www.roblox.com/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : https://en.help.roblox.com/hc/en-us/articles/115004647846-Roblox-Terms-of-Use
* Comment (anything else which might help) : 
Please create a version of Roblox that does not require installation.
thank you!

**Comment by crazy-max** [comment]
Duplicated of #22
