### ISSUE TITLE
Sourcetree for Windows

### ISSUE THREAD

**Issue by yetangye** [portapps/portapps#139]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Sourcetree for Windows
* Description : A git gui client
* Website : https://www.sourcetreeapp.com/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Atlassian Software License
* Comment (anything else which might help) : Nothing

**Comment by crazy-max** [comment]
@yetangye According to their [Software License Agreement](https://www.atlassian.com/legal/software-license-agreement), it's not allowed to redistribute their product.
