### ISSUE TITLE
MEmu

### ISSUE THREAD

**Issue by seiya-git** [portapps/portapps#14]
* Name : MEmu
* Description : MEmu App Player is a powerful Android emulator and aims to provide the best experience to play android games and apps on PC. Because of the leading performance and unique multiple-Android-kernels support, MEmu has more than 20 million users in over 200 countries and 20 languages, and it’s still growing rapidly.
* Website : https://www.memuplay.com/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Freeware
* Comment (anything else which might help) : Have MEmuCommand
https://www.memuplay.com/blog/2018/11/27/memucommand-reference-manual/

**Comment by crazy-max** [comment]
According to their [TOS](https://www.memuplay.com/agreement.html), it's not allowed to redistribute their product.
