### ISSUE TITLE
Use larger icons

### ISSUE THREAD

**Issue by xmha97** [portapps/portapps#140]
Hi,
Please use larger icons (256x256)
![Windows File Explorer](https://user-images.githubusercontent.com/23485114/89691410-261e7d00-d91e-11ea-8107-6518be071835.png)

**Comment by crazy-max** [comment]
@xmha97 It's fixed for the portable wrapper (Portapps 2.6.0) but for the InnoSetup portable installer this is not currently possible (limitation on their side).

**Comment by xmha97** [comment]
> 
> 
> @xmha97 It's fixed for the portable wrapper (Portapps 2.6.0) but for the InnoSetup portable installer this is not currently possible (limitation on their side).

Okay, Thanks for following up.
