### ISSUE TITLE
Filmora

### ISSUE THREAD

**Issue by UnityUser05** [portapps/portapps#145]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : iamthetrueyes
* Description : Please make this a portapp
* Website : https://filmora.wondershare.net/video-editor-software/?gclid=Cj0KCQjwp4j6BRCRARIsAGq4yMFsH1T3nlfEjUWOwgeTpomdT-42VM7OGXRSep6s3xyqO7af2qc5iEkaApGOEALw_wcB
* License (e.g. Freeware, OSS, GPL, MIT, etc) : 
* Comment (anything else which might help) :

**Comment by crazy-max** [comment]
Hi @UnityUser05, sorry for closing this issue, your link was marked as a malware.
