### ISSUE TITLE
Microsoft Edge

### ISSUE THREAD

**Issue by yekanchi** [portapps/portapps#148]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Microsoft Edge (Chromium Based) Browser 
* Description :  Web Browser
* Website : https://www.microsoft.com/en-us/edge
* License (e.g. Freeware, OSS, GPL, MIT, etc) :  proprietary 
* Comment (anything else which might help) : newer versions are chromium based

**Comment by crazy-max** [comment]
Duplicated of #102

**Comment by crazy-max** [comment]
@yekanchi According to their Terms of Use, it's not allowed to redistribute their product.
