### ISSUE TITLE
Remove Deprecated pakcages(syscall)

### ISSUE THREAD

**Issue by ProblematicDude** [portapps/portapps#149]
As title says you should consider updating the source code so it stays updated.  File **_'util/win/version.go'_** contains **_'syscall'_** package and as
[https://golang.org/pkg/syscall/](url) ,  says 
**Deprecated: this package is locked down. Callers should use the corresponding package in the golang.org/x/sys repository instead.**
Can you update the code ?

**Comment by crazy-max** [comment]
@ProblematicDude Thanks for your input! I will fix this.
