### ISSUE TITLE
Messenger (By Facebook) Official (Non UWP Metro ) Native app.

### ISSUE THREAD

**Issue by Abdullah-Haque** [portapps/portapps#163]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Messenger(By Facebook)
* Description : Facebook offcially released messenger desktop( Non-UWP Metro) native app for windows which uses electron
* Website : [Official site](https://www.messenger.com/desktop/) [Direct download link](https://scontent.fdac30-1.fna.fbcdn.net/v/t39.2270-6/10000000_34426668046934777_5869490702847390423_n.exe/Messenger.83.5.128.exe?_nc_cat=1&ccb=2&_nc_sid=435822&_nc_eui2=AeH1IezhFSf8gs6acW78lHdKS_OCKUVMXNlL84IpRUxc2V3wgF49iJVeCt_p-om7JOHTOoV_TApfAasrAe3k6ilh&_nc_ohc=1ghG-RTnfe8AX-lzInT&_nc_ht=scontent.fdac30-1.fna&oh=6b04d119a62e1f31dff94d3f8c7b9a03&oe=600134E1&dl=1)
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Freeware
* Comment (anything else which might help) : Electron App, Writes to Appdata:Local and Roaming...No Registry writings if installer(Using universal extractor)  extracted .

**Comment by Abdullah-Haque** [comment]
@crazy-max

**Comment by crazy-max** [comment]
@Abdullah-Haque According to their Terms of Use, it's not allowed to redistribute their product. But you can use [Caprine portable](https://portapps.io/app/caprine-portable/) as an alternative.
