### ISSUE TITLE
Signal

### ISSUE THREAD

**Issue by ProblematicDude** [portapps/portapps#171]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Signal
* Description : Messaging app
* Website : https://signal.org/en/
* Comment (anything else which might help) : Signal now a days is the new cool but it dont have its portable version can you look forward in this port.

**Comment by crazy-max** [comment]
* Description : Signal is a cross-platform centralized encrypted messaging service developed by the Signal Foundation and Signal Messenger
* Website : https://signal.org
* License (e.g. Freeware, OSS, GPL, MIT, etc) : AGPL-3.0

**Comment by crazy-max** [comment]
@ProblematicDude Available: https://portapps.io/app/signal-portable/
