### ISSUE TITLE
Whatsapp

### ISSUE THREAD

**Issue by pedroserpa** [portapps/portapps#18]
> Please follow the following guide to file a proper request report : https://portapps.io/doc/request-apps/

* Name : Whatsapp Desktop
* Description : With WhatsApp, you'll get fast, simple, secure messaging and calling for free*, available on phones all over the world.
* Website : https://whatsapp.com
* License (e.g. Freeware, OSS, GPL, MIT, etc) : 
* Comment (anything else which might help) :

**Comment by crazy-max** [comment]
@pedroserpa WhatsApp portable is now available : https://portapps.io/app/whatsapp-portable/

**Comment by Cyberavater** [comment]
Thanks!
