### ISSUE TITLE
WampServer

### ISSUE THREAD

**Issue by zpcol** [portapps/portapps#180]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : WampServer
* Description : WampServer is a Windows web development environment. It allows you to create web applications with Apache2, PHP and a MySQL database. Alongside, PhpMyAdmin allows you to manage easily your databases.

* Website : https://www.wampserver.com, https://sourceforge.net/projects/wampserver/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : GNU GPL 
* Comment (anything else which might help) :

**Comment by crazy-max** [comment]
@zpcol See [Neard](https://neard.io/) as portable WAMP.

**Comment by zpcol** [comment]
neard 1.8.2
error while starting mysql services
windows 10 1909.753_Pro_x64
