### ISSUE TITLE
qBittorrent

### ISSUE THREAD

**Issue by z3huti** [portapps/portapps#185]
you dont need to make portable for qBittorrent 

qBittorrent is portable already, read this https://github.com/qbittorrent/qBittorrent/wiki/How-to-use-portable-mode

**Comment by crazy-max** [comment]
@z3huti Portapps allow to automate this procedure without the pain of flags or subcommands for the end user. Feel free to use this "How to" if you prefer ofc.

**Comment by z3huti** [comment]
> @z3huti Portapps allows to automate this procedure without the pain of flags or subcommands for the end user. Feel free to use this "How to" if you prefer ofc.

Your Portapps is for windows only, yes? But in windows for qBittorrent you just need to create a folder called "profile" in the same directory as the qbittorrent.exe and you are done. No flags or subcommands.

**Comment by crazy-max** [comment]
@z3huti Yes that's true my bad but with portapps we makes things more consistent with the `data` folder. What's your request btw? Removing qBittorrent from portapps?

**Comment by z3huti** [comment]
> @z3huti Yes that's true my bad but with portapps we make things more consistent with the `data` folder. What's your request btw? Removing qBittorrent from portapps?

Dont have to remove it from Portapps. Maybe just put info or\and  link, how to make qBittorrent portable.
