### ISSUE TITLE
Silent install issue

### ISSUE THREAD

**Issue by xylltch** [portapps/portapps#186]
I'm trying to write an update script to automatically download and install new versions of certain apps.  I've got everything working except I'm having trouble getting the app installers to run silently. I can pass directories to the installer without issue, but if I try and run an installer with /SILENT or /VERYSILENT the installer fails.

Are silent installs possible or something that could be supported? It could be that I'm simply missing some step, please let me know if that's the case.

I've attached a log file for both a normal install and when trying to use the /SILENT option
[innolognormal.txt](https://github.com/portapps/portapps/files/6111459/innolognormal.txt)
[innologsilent.txt](https://github.com/portapps/portapps/files/6111460/innologsilent.txt)

**Comment by crazy-max** [comment]
@xylltch You could download the 7z archives instead.
