### ISSUE TITLE
Borderless-Gaming

### ISSUE THREAD

**Issue by Cyberavater** [portapps/portapps#19]
> Please follow this guide to file a proper request report: https://portapps.io/doc/request-apps/

* Name: Borderless-Gaming
* Description: Borderless Gaming is a simple tool that will allow you to turn your windowed video games into "fullscreen" applications without all of the negative side effects
* Website: https://github.com/Codeusa/Borderless-Gaming
* License (e.g. Freeware, OSS, GPL, MIT, etc): The project is open source under the GNU General Public License v2.0.
* Comment (anything else which might help): DL; https://github.com/Codeusa/Borderless-Gaming/releases

**Comment by Cyberavater** [comment]
Btw, this link is dead; https://portapps.io/doc/request-apps/
it should be "app" instead of "apps"

**Comment by crazy-max** [comment]
@Cyberavater Borderless Gaming portable is now available : https://portapps.io/app/borderless-gaming-portable/
Spread the word :)

**Comment by Cyberavater** [comment]
Thanks friend :)
