### ISSUE TITLE
Jitsi

### ISSUE THREAD

**Issue by etconsilium** [portapps/portapps#192]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Jitsi Meet (Free Video Conferencing Solutions)
* Description : Jitsi Meet is an open source JavaScript WebRTC application used primarily for video conferencing. In addition to audio and video, screen sharing is available, and new members can be invited via a generated link. The interface is accessible via web browser or with a mobile app. The Jitsi Meet server software can be downloaded and installed on Linux-based computers. Jitsi owner 8x8 maintains a free public-use server for up to 50 participants at meet.jit.si https://en.wikipedia.org/wiki/Jitsi#Jitsi_Meet
* Website : https://jitsi.org/jitsi-meet/ 
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Jitsi is distributed under the terms of the Apache License, Version 2.0
* Comment (anything else which might help) : 
Desktops client https://desktop.jitsi.org/Main/Download.html 
Desktops client Electron powered https://github.com/jitsi/jitsi-meet-electron/

**Comment by crazy-max** [comment]
@etconsilium Duplicate #120
