### ISSUE TITLE
Discord Canary

### ISSUE THREAD

**Issue by m1lxs** [portapps/portapps#194]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Discord Canary
* Description : Basically Discord but with some tweaks and features that are not in the normal Discord
* Website : canary.discord.com
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Freeware?
* Comment (anything else which might help) : 
By making [Discord Canary](https://canary.discord.com) a Portable App, people will be less likely to be Token Grabbed (a form of account stealing on discord) and I'm pretty sure it will also have many other advantages.

**Comment by crazy-max** [comment]
Duplicate #193
