### ISSUE TITLE
Oracle VM VirtualBox

### ISSUE THREAD

**Issue by JotaOdiceu** [portapps/portapps#195]
* Name : Oracle VM VirtualBox
* Description : VirtualBox is a general-purpose full virtualizer for x86 hardware, targeted at server, desktop and embedded use. 
* Website : https://www.virtualbox.org/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : GPL
* Comment (anything else which might help) : It allows the creation of virtual machines on computers, a portable version would make these machines transportable anywhere. The update cycle is very long and stable.

**Comment by crazy-max** [comment]
Duplicate #112
