### ISSUE TITLE
Lightcord

### ISSUE THREAD

**Issue by FieryMewtwo** [portapps/portapps#198]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Lightcord
* Description : A Discord Client with BetterDiscord integration out of the box
* Website : github.com/Lightcord/Lightcord
* License (e.g. Freeware, OSS, GPL, MIT, etc) : MIT
* Comment (anything else which might help) :  Lightcord has a "portable" mode, but it installs many things to AppData. It's also buggy.

**Comment by DodoGames7** [comment]
thats a good app request lol

**Comment by FieryMewtwo** [comment]
How is this considered spam?

**Comment by FieryMewtwo** [comment]
> thats a good app request lol

I'm dead serious

**Comment by IntoTheVoid-900** [comment]
Lightcord has been discontinued.

**Comment by FieryMewtwo** [comment]
Haha sorry I forgot to close this issue...
