### ISSUE TITLE
Is This a False Alarm In Skype (Trojan)

### ISSUE THREAD

**Issue by taskmann** [portapps/portapps#2]
Hello Developer,

Thanks for the great work!

Each time I unzip portable skype Windows Defender (Windows 10) detect this trojan 

Trojan:Win32/Zpevdo.A

Should I be concerned about this?

**Comment by crazy-max** [comment]
Hi @taskmann,
Please create your issue on [skype-portable repository](https://github.com/portapps/skype-portable/issues). This one is core specific. Thanks :)
