### ISSUE TITLE
Mozilla Thunderbird

### ISSUE THREAD

**Issue by SappFi** [portapps/portapps#20]
* Name : Mozilla Thunderbird
* Description : FLOSS Email client, news client, feed reader, chat (XMPP, IRC, Twitter) client, and an optional PIM (extension).
* Website : [thunderbird.net](https://www.thunderbird.net) | [web ftp/cdn repo](https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/latest) | [SCM](https://hg.mozilla.org/comm-central/)
* License (e.g. Freeware, OSS, GPL, MIT, etc) : OSS::MPL 2.0
* Comment (anything else which might help) : a [portableapps.com-based](http://portableapps.com/apps/internet/thunderbird_portable) version exists already, (also availalble in beta), but I haven't tested it yet, so a first logical consideration would require to evaluate the relevence of a portapps-based version.

**Comment by crazy-max** [comment]
@SappFi Thunderbird portable has been added to Portapps. You can check the list of modifications here : https://portapps.io/app/thunderbird-portable/#infos

**Comment by SappFi** [comment]
@crazy-max 
I stopped using the PApps platform long time ago has most of their ported app are not maintained up-to-date.. Using scoop instead (which is very "FLOSS + Portable"-minded)

But I'll look at all of the available option for sure. thanks for sharing tho !
If you need help of any kind let me know. Let's unroot ourselves :)
