### ISSUE TITLE
Mozilla Firefox

### ISSUE THREAD

**Issue by andreawilson22** [portapps/portapps#207]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name :  Mozilla Firefox
* Description : web brower
* Website : https://www.mozilla.org/en-US/firefox
* License (e.g. Freeware, OSS, GPL, MIT, etc) : 
* Comment (anything else which might help) : There is already a portable version available at portableapps.com, but it would be nice to have it on portapps.io as well.

**Comment by crazy-max** [comment]
https://github.com/portapps/phyrox-portable
