### ISSUE TITLE
Request: NodeJS

### ISSUE THREAD

**Issue by maya95-cyber** [portapps/portapps#209]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : NodeJS
* Description : A JavaScript runtime built on Chrome's V8 JavaScript engin
* Website : https://nodejs.org/en/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : MIT
* Comment (anything else which might help) :

**Comment by Bellisario** [comment]
Have a look here: https://github.com/crazy-max/nodejs-portable

It is made by the creator of **portapps** @crazy-max, but it isn't published on **portapps** repo or site... :cry:

**Comment by crazy-max** [comment]
#72
