### ISSUE TITLE
Enhancement: Provide distinctions information against the already existing portable ports

### ISSUE THREAD

**Issue by SappFi** [portapps/portapps#21]
For exemple, KiTTY was ported to portable builds already.. Having some information on what differs from this portapps version against all of the other available portable port would be greatly appreciated. 
for instance, what make each of those different from this portapps version:
- the [official build](http://www.9bis.net/kitty/Portability), which can be run in portable mode already
- the [portableapps.com version](https://portableapps.com/apps/internet/kitty-portable)
- that [choco-repacked version](https://chocolatey.org/packages/kitty), installed with the `/portable` switch

**Comment by crazy-max** [comment]
Hi @SappFi, I have already started something like that for [Firefox portable](https://portapps.io/app/firefox-portable/#infos) where I explain the changes made. I will made the list of modifications for the others.

**Comment by crazy-max** [comment]
@SappFi List of changes has been added for KiTTY : https://portapps.io/app/kitty-portable/#infos
