### ISSUE TITLE
portableapps.com like platform launcher & updater

### ISSUE THREAD

**Issue by maya95-cyber** [portapps/portapps#211]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Portapps.io System Menu
* Description :  Request a PortableApps.com like platform menu system.
* Website : https://portableapps.com/news/2021-06-15--portableapps.com-platform-18.0.1-released
* License (e.g. Freeware, OSS, GPL, MIT, etc) : 
* Comment : Can we have a PortableApps.com like apps downloader/updater menu system ?  It will be much easier to download & update apps in a central place instead download & update apps individually.

**Comment by crazy-max** [comment]
https://github.com/portapps/portapps/issues/37
