### ISSUE TITLE
Roblox

### ISSUE THREAD

**Issue by vikktrey123** [portapps/portapps#22]
* Name : Roblox
* Description :  Roblox is a massively multiplayer online and game creation system platform that allows users to design their own games and play a wide variety of different types of games created by other users. The platform hosts social network games constructed of Lego-like virtual blocks.
* Website : https://roblox.com
* License (e.g. Freeware, OSS, GPL, MIT, etc) : UGC (i guess)
* Comment (anything else which might help) :  my laptop is absolute garbage so this would be useful

**Comment by crazy-max** [comment]
Accodring to their [TOS](https://en.help.roblox.com/hc/en-us/articles/115004647846-Roblox-Terms-of-Use), it's not allowed to redistribute their product.
