### ISSUE TITLE
Whatsapp portable doesn't start 2.2132.6 (Windows 10 20H2)

### ISSUE THREAD

**Issue by mxuper** [portapps/portapps#220]
Whatsapp portable  2.2132.6 (Winows 10 20H2) Doesn't start
an error like this is given
![Screenshot_2](https://user-images.githubusercontent.com/90188188/132202405-f83660f9-53f5-4afe-a5ec-72f5858ff985.jpg)

**Comment by crazy-max** [comment]
https://github.com/portapps/whatsapp-portable/issues/39
