### ISSUE TITLE
Can you provide a configuration file to automatically generate portable software?

### ISSUE THREAD

**Issue by lun9090** [portapps/portapps#222]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Configure and generate portable software
* Description : 
* Website : 
* License (e.g. Freeware, OSS, GPL, MIT, etc) : 
* Comment (anything else which might help) : 

It is suggested that we can generate portable versions of any software based on this platform.

**Comment by crazy-max** [comment]
https://github.com/portapps/portapps/issues/90
