### ISSUE TITLE
IGram For Desktop 4.00

### ISSUE THREAD

**Issue by danielsousa1985** [portapps/portapps#23]
I have an other suggestion. IGram for Desktop. You ask Why IGram not Telegram. Because the Telegram for Windows is not accessible for us, blind people. The IGram is the most accessible. The download link is https://i-gram.org/files/isetup.4.0.0.exe> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : 
* Description : 
* Website : 
* License (e.g. Freeware, OSS, GPL, MIT, etc) : 
* Comment (anything else which might help) :

**Comment by crazy-max** [comment]
@danielsousa1985 Please modify your request and fill in the missing fields

**Comment by crazy-max** [comment]
Closed due to inactivity
