### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by talha-exe** [portapps/portapps#235]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Telegram
* Description : A telegram is a message sent by a telegraph, which is also called a wire. Over time, there have been many means of communicating, such as messenger pigeon, telephone, text message, letter, and email. Another is the telegram, which is a message sent by a telegraph.
* Website : www.telegram.org
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Freeware
* Comment (anything else which might help) :

**Comment by mjrawesome** [comment]
Telegram already has a portable version, see [telegram](https://desktop.telegram.org/ ) or [github](https://github.com/telegramdesktop/tdesktop/releases) ([download](https://telegram.org/dl/desktop/win64_portable))

**Comment by kowalwsky** [comment]
yes, but yours is better and need 3x  fewer ram as the original one. I have 3.3 x64.

**Comment by crazy-max** [comment]
https://github.com/portapps/portapps/issues/70#issuecomment-537133016
