### ISSUE TITLE
32 bit update

### ISSUE THREAD

**Issue by liqideqq** [portapps/portapps#238]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Ungoogled Chromium portable 96.0.4664.45-12 x32
* Description : 32 bit request to update the latest, ok?
* Website : https://portapps.io/news/2021-11-22-ungoogled-chromium-portable-96.0.4664.45-12/

**Comment by crazy-max** [comment]
https://github.com/portapps/ungoogled-chromium-portable/issues/33#issuecomment-1023708254
