### ISSUE TITLE
Zello

### ISSUE THREAD

**Issue by danielsousa1985** [portapps/portapps#24]
I have an other suggestionI have a new suggestion. O Zello. If the battery of an iPhone, or an Android is gone and if we are on a computer in a youth club or cyber cafe and we can not install it like we will? So it would be good to propose this program to you.> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : 
* Description : 
* Website : 
* License (e.g. Freeware, OSS, GPL, MIT, etc) : 
* Comment (anything else which might help) :

**Comment by crazy-max** [comment]
@danielsousa1985 Please modify your request and fill in the missing fields

**Comment by crazy-max** [comment]
Closed due to inactivity
