### ISSUE TITLE
OBS Studio

### ISSUE THREAD

**Issue by gitmodder** [portapps/portapps#241]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : OBS Studio
* Description : Free and open source software for video recording and live streaming.
* Website : https://obsproject.com/
* License (e.g. Freeware, OSS, GPL, MIT, etc) :  Freeware
* Comment (anything else which might help) :

**Comment by crazy-max** [comment]
https://github.com/portapps/portapps/issues/141
