### ISSUE TITLE
Github Desktop

### ISSUE THREAD

**Issue by Cwavs** [portapps/portapps#243]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Github Desktop
* Description : A Desktop client for Github.
* Website : https://desktop.github.com/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : MIT
* Comment (anything else which might help) : Github repo: https://github.com/desktop/desktop. A previous issue discussing an official portable release: https://github.com/desktop/desktop/issues/10298.

**Comment by crazy-max** [comment]
https://github.com/portapps/portapps/issues/87#issuecomment-552160540
