### ISSUE TITLE
mIRC

### ISSUE THREAD

**Issue by Cyberavater** [portapps/portapps#26]
> Please follow this guide to file a proper request report: https://portapps.io/doc/request-app/

* Name: mIRC
* Description: mIRC is a full featured Internet Relay Chat client for Windows that can be used to communicate, share, play or work with others on IRC networks around the world, either in multi-user group conferences or in one-to-one private discussions.
* Website: https://www.mirc.com/index.html
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Proprietary/Trialware
* Comment (anything else which might help): Disable auto-update

**Comment by crazy-max** [comment]
@Cyberavater mIRC portable is now available : https://portapps.io/app/mirc-portable/

**Comment by Cyberavater** [comment]
Okay, Thanks @crazy-max .

**Comment by Cyberavater** [comment]
Can you update it to 7.56

**Comment by crazy-max** [comment]
@Cyberavater Done
