### ISSUE TITLE
Newsleecher

### ISSUE THREAD

**Issue by terrorfreak2** [portapps/portapps#27]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Newsleecher
* Description : Newsleecher latest
* Website : www.Newsleecher.com
* License (e.g. Freeware, OSS, GPL, MIT, etc) : paid
* Comment (anything else which might help) : Newsleecher 7.0 latest version

**Comment by crazy-max** [comment]
Hi @terrorfreak2, newsleecher seems outdated (6 Jun. 2016) and [not maintained anymore](https://www.newsleecher.com/forum/viewtopic.php?f=4&t=27001). Have you tried [NZBGet](https://nzbget.net/) ?

**Comment by crazy-max** [comment]
Closed due to inactivity
