### ISSUE TITLE
MongoDB Compass

### ISSUE THREAD

**Issue by azhe403** [portapps/portapps#276]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : MongoDB Compass
* Description : Compass is an interactive tool for querying, optimizing, and analyzing your MongoDB data. Get key insights, drag and drop to build pipelines, and more.
* Website : https://www.mongodb.com/products/compass
* License (e.g. Freeware, OSS, GPL, MIT, etc) : SSPL
* Comment (anything else which might help) : there are available zip package, but config files not stored on current directory

**Comment by crazy-max** [comment]
Does not seem redistributable: https://www.mongodb.com/licensing/server-side-public-license

> You may convey verbatim copies of the Program's source code as you receive it, in any medium, provided that you conspicuously and appropriately publish on each copy an appropriate copyright notice; keep intact all notices stating that this License and any non-permissive terms added in accord with section 7 apply to the code; keep intact all notices of the absence of any warranty; and give all recipients a copy of this License along with the Program.
