### ISSUE TITLE
Transmission 4.00 Beta

### ISSUE THREAD

**Issue by MrxHellsing** [portapps/portapps#277]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Transmission 4.0.0.Beta-1-x64
* Description : BitTorrent Client
* Website : https://transmissionbt.com/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : GNU GPLv2 & GNU GPLv3 & Mnemosyne LLC
* Comment (anything else which might help) : The new Beta version claims to be resource efficient.  More details here : https://github.com/transmission/transmission/releases/tag/4.0.0-beta.1

**Comment by crazy-max** [comment]
Please do not open app request for app already available: https://portapps.io/app/transmission-portable/. Thanks.
