### ISSUE TITLE
Config to place bin (app dir) at another place

### ISSUE THREAD

**Issue by kolobok55** [portapps/portapps#28]
I want to create several brave portable copies to have own configs, extension, etc in each. But I want to share app dir, cs it same for all and it can save quote of storage place.
Does any config to do it - run brave with app in another place?

**Comment by crazy-max** [comment]
This feature is now implemented in Portapps 1.23.0 and will be available for future versions of apps in the catalog.

**Comment by crazy-max** [comment]
More info about the implmentation : https://portapps.io/doc/configuration/ (app_path)

**Comment by caspertone2003** [comment]
@crazy-max 
Thanks for this!
Eager to test it.

Then, the app folder can be moved to "app_path" location, while the all other files/folders must be left in the place where  we keep [appname]-portable.yml (that must point via app_path: to the location of app folder).

Do I understand right the way to use it?

It seems the only way to do it, but it is not 100% clear in https://portapps.io/doc/configuration/

**Comment by crazy-max** [comment]
@caspertone2003 That's it!

**Comment by caspertone2003** [comment]
no go... from log:

Wed, 08 May 2019 CEST FTL C:/Users/travis/build/portapps/brave-portable/main.go:28 > Cannot initialize application. See log file for more info. error="open E:\\_______Brave\\PER\\_SW-Windows_Brave-0.63.55-16\\portapp.json: System cannot find specified file." portapps.json
