### ISSUE TITLE
Brave Portable Version Update

### ISSUE THREAD

**Issue by MrxHellsing** [portapps/portapps#281]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Brave
* Description : Browser
* Website : https://brave.com/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : [Mozilla Public License 2.0](https://choosealicense.com/licenses/mpl-2.0/)
* Comment (anything else which might help) : 
![image](https://user-images.githubusercontent.com/29206412/201464507-c60e73d3-7f39-4c04-a48d-9599fb2cd78b.png)

Browser needs to be updated to receive ads. The current portable version is 1.43.89.

**Comment by sakibarifin** [comment]
I believe brave was updated recently.

**Comment by crazy-max** [comment]
An app request is for app creation not for update. Please open an issue on brave repo instead.
