### ISSUE TITLE
CurseForge wow addon

### ISSUE THREAD

**Issue by wazerstar** [portapps/portapps#283]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : CurseForge
* Description :  Addon updater for wow
* Website : https://download.curseforge.com/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : https://www.overwolf.com/legal/terms
* Comment (anything else which might help) : Curse was once a solo application, but today its forced with overwolf application upon when we want to update our addons, would be really cool to have this as portable and without the need to actually start overwolf but just simply curseforge addon updater, that said maybe something from the overwolf service had to stay in the background, and I guess thats OK as long you just use curseforge as your normally would.

**Comment by crazy-max** [comment]
Not allowed to distribute per TOS: https://www.overwolf.com/legal/terms

> Overwolf and/or its licensors own the Services, including all worldwide intellectual property rights in the Services, and the trademarks, service marks, and logos contained therein. Please note that the Third-Party Apps/Mods are owned by the applicable developers. Overwolf hereby grants you a limited, revocable, non sublicensable license to use the Services solely for your personal use. Except as expressly permitted herein, you may not copy, further develop, reproduce, republish, modify, alter, download, post, broadcast, transmit or otherwise use the Services. All rights not granted to you herein are reserved to Overwolf and/or its licensors. You will not remove, alter or conceal any copyright, trademark, service mark or other proprietary rights notices incorporated in the Content or Services.
