### ISSUE TITLE
I need brave portable provided that the path (app_path) is determined during installation as desired in any partition

### ISSUE THREAD

**Issue by elodamy** [portapps/portapps#285]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : 
* Description : 
* Website : 
* License (e.g. Freeware, OSS, GPL, MIT, etc) : 
* Comment (anything else which might help) :

**Comment by crazy-max** [comment]
This is not the right repo. Please open an issue on brave repo instead: https://github.com/portapps/brave-portable
