### ISSUE TITLE
Better Discord (based on "Stable" version) Portable

### ISSUE THREAD

**Issue by J0E9411** [portapps/portapps#286]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : BetterDiscord
* Description : A Discord Client with BetterDiscord integration out of the box
* Website : https://github.com/BetterDiscord/BetterDiscord
* License (e.g. Freeware, OSS, GPL, MIT, etc) : MIT
* Comment (anything else which might help) : Would be awesome to have a portable version of BetterDiscord (applied on the "Stable" version of discord, no PTB or Canary).

**Comment by crazy-max** [comment]
This is not a standalone app but an extension of Discord. As discussed in https://github.com/portapps/discord-portable/issues/63 and https://github.com/portapps/discord-portable/issues/79 we don't bring support for this extension but feel free to contribute if you want it back.
