### ISSUE TITLE
Dropbox

### ISSUE THREAD

**Issue by vbprofi** [portapps/portapps#290]
* Name : Dropbox
* Description : Dropbox is a personal cloud storage service (sometimes referred to as an online backup service) that is frequently used for file sharing and collaboration. The Dropbox application is available for Windows, Macintosh and Linux desktop operating systems.
* Website : [https://www.dropbox.com](https://www.dropbox.com/)
* License (e.g. Freeware, OSS, GPL, MIT, etc) : limited, nonexclusive, nontransferable, revocable license to use the Software
* Comment (anything else which might help) : 
Hello,
Is it possible for you to add Dropbox to your amazing collection of portable apps?
Dropbox AHK is no longer being developed. The last version is from 2019.
Would be nice if you could develop an alternative to this.
Thank you in advance!
best regards

**Comment by crazy-max** [comment]
Protected by copyright and trademark https://www.dropbox.com/terms

> The Services are protected by copyright, trademark, and other US and foreign laws. These Terms don’t grant you any right, title, or interest in the Services, others’ content in the Services, Dropbox trademarks, logos and other brand features.
