### ISSUE TITLE
Update Signal to latest version

### ISSUE THREAD

**Issue by cmenglish** [portapps/portapps#291]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Signal
* Description : secure private messaging
* Website : signal.org
* License (e.g. Freeware, OSS, GPL, MIT, etc) : 
* Comment (anything else which might help) : Signal portable is a few version out of date, could we get an up-to-date version? Thanks!

**Comment by IchBinGROOT** [comment]
This problem persists for a long time now, [here](https://github.com/portapps/signal-portable/issues/24) you can find a workaround.

**Comment by cmenglish** [comment]
Thanks!
