### ISSUE TITLE
1password 8

### ISSUE THREAD

**Issue by Kliammmm213** [portapps/portapps#299]
* Name : 1password 8
* Description : 1password's password manager
* Website : https://1password.com
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Freeware
* Comment (anything else which might help) : -

**Comment by crazy-max** [comment]
Not allowed to redistribute their product per TOS: https://1password.com/legal/terms-of-service/

> The Service and all contents, including but not limited to text, images, graphics or code are the property of AgileBits Inc. and are protected by copyright, trademarks, database and other intellectual property rights. You may display and copy, download or print portions of the material from the different areas of the Service only for your own non-commercial use. Any other use is strictly prohibited and may violate copyright, trademark and other laws. These Terms do not grant you a license to use any trademark of AgileBits Inc. or its affiliates. You further agree not to use, change or delete any proprietary notices from materials downloaded from the Service.
