### ISSUE TITLE
Franz 5

### ISSUE THREAD

**Issue by shadilahham** [portapps/portapps#30]
* Name : Franz 5
* Description : messaging app for WhatsApp, Facebook Messenger, Slack, Telegram, etc.
* Website : https://github.com/meetfranz/franz
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Apache License 2.0
* Comment (anything else which might help) : Several requests for official portable version but comments by the developers. https://github.com/meetfranz/franz/issues/912 currently I wasn't able to find any portable version implementation online.

**Comment by crazy-max** [comment]
Hi @shadilahham,

Looking quickly, I see that this application is based on Electron, so it will be quite easy to make this application portable through Portapps. I'll keep you in touch.

**Comment by crazy-max** [comment]
@shadilahham Franz is now available : https://portapps.io/app/franz-portable/

**Comment by shadilahham** [comment]
> @shadilahham Franz is now available : https://portapps.io/app/franz-portable/

@crazy-max wow that was super fast! thanks! hope this will be useful to all portable app lovers :)
