### ISSUE TITLE
Whale Browser

### ISSUE THREAD

**Issue by bl4ckh47h4ck3r** [portapps/portapps#31]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Whale Browser
* Description : Experience it. You'll find out.
* Website : https://whale.naver.com/en
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Chromium Based

**Comment by crazy-max** [comment]
Microsoft Edge is a core component of Windows and cannot be "portapped"

**Comment by MithilMajumder** [comment]
Ok then try `Whale Browser`

**Comment by crazy-max** [comment]
As Whale is a Chromium based browser, consider [this limitation](https://github.com/portapps/portapps/issues/3#issuecomment-441379107).

**Comment by MithilMajumder** [comment]
If you need any help porting software then I can help you.
Here I am giving a [link]((http://effect8.ru/) where this guy is making portable browser with some tweak like you to boost up productivity

**Comment by crazy-max** [comment]
According to their [TOS](https://whale.naver.com/legal/terms/en/), it's not allowed to redistribute their product.
