### ISSUE TITLE
Signal .exe file hangs on launch

### ISSUE THREAD

**Issue by krys0100** [portapps/portapps#317]
Hello, 
I'm trying to use Signal Portable on my work computer (Windows 10 Pro, x64, 11th Gen Intel, Microsoft Surface).   

(I don't want to ask my IT department about this issue, as I'm not sure this is completely kosher.)   

When I launch my app it hangs on the screen shown in the attached image and I have to kill it with the task manager.   Any suggestions?   

Thanks in advance, and have a good day.

PS:   I hope this is the proper place to post this.   I'm new to GitHub and also couldn't find the link to post issues from the Portable Apps website.   I had to access this through the "Request a new app" link and then chose a "blank issue".  

PSS:   The image-upload-feature resulted in an error, so I'll post it here:  https://postimg.cc/qzGHPMg1

**Comment by crazy-max** [comment]
This repo is not intended for specific app support. For Signal go to https://github.com/portapps/signal-portable. Thanks
