### ISSUE TITLE
Handle Application User Model ID

### ISSUE THREAD

**Issue by beppe9000** [portapps/portapps#34]
#### Steps to reproduce this issue

Windows 10

1. Pin the portable executable to the taskbar
2. Click it

#### Expected behaviour

Firefox uses the pinned icon

#### Actual behaviour

There is an additional icon

RElated: https://github.com/MrAlex94/Waterfox/issues/91

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :
Latest Firefox Portable "1.23.0"

**Operating system (ex. Windows 10 Pro 64 bits)** :
Windows 10

**Comment by beppe9000** [comment]
I'm sure the api needs to be tested using the information from the issue i linked in the op too.

Ps. nice, didn't know issues can be migrated like this...

**Comment by crazy-max** [comment]
@beppe9000 After several researches and tests, the Application User Model ID is well taken into account.

I tried with several applications like Brave by creating a shortcut to `brave-portable.exe` and putting it in the taskbar and running several instances and these are well grouped. Same thing if I open a new window from Brave:

![image](https://user-images.githubusercontent.com/1951866/59531197-9e89d980-8ee5-11e9-9eb4-806cc9f3ce26.png)
