### ISSUE TITLE
Requesting for Microsoft Edge browser portable esp., 89 and versions before AI garbage like 95 not after it with no auto-update or matching or overlapping with desktop installed version. PLEASE.

### ISSUE THREAD

**Issue by varnit-nigam** [portapps/portapps#343]
### Request guidelines

- [X] I've read the [request guidelines](https://portapps.io/doc/request-app/)

### I've checked that that ...

- [X] ... license allows distribution/repackaging of the software
- [X] ... this is not an abdandonware

### Name

Microsoft Edge

### Description

Requesting for Microsoft Edge browser portable esp., 89 and versions before AI garbage like 95 not after it with no auto-update or matching or overlapping with desktop installed version. 

Older versions were functional, usable, faster and has less bloatware and came with clean UI.

PLEASE.

### Website

https://www.microsoft.com/en-us/edge/business/download?form=MA13FJ

### License

-

### TOS link

-

### Additional info

Requesting for Microsoft Edge browser portable esp., 89 and versions before AI garbage like 95 not after it with no auto-update or matching or overlapping with desktop installed version. 

Older versions were functional, usable, faster and has less bloatware and came with clean UI.

PLEASE.

https://blogs.windows.com/msedgedev/2021/03/04/edge-89-performance/

https://mspoweruser.com/microsoft-edge-89-stable/

https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel

https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-archive-stable-channel

![chrome_sPENSXZhlx](https://github.com/portapps/portapps/assets/156216269/41012b8c-473a-4d1f-8e60-d5a956031438)

**Comment by crazy-max** [comment]
Not allowed to redistribute their product per Microsoft TOS.
