### ISSUE TITLE
Cannot change app folder path

### ISSUE THREAD

**Issue by caspertone2003** [portapps/portapps#35]
I tried v 17. I have been unable to use it separaring app and the rest of files in different folders, as was running smoothly in v16.

I receive a:
![image](https://user-images.githubusercontent.com/4682903/57843866-4751f580-77cf-11e9-8f7a-4feca3267916.png)

Any hint?

Thanks!

**Comment by crazy-max** [comment]
@caspertone2003 This is fixed, I'll run a new build of brave-portable that will integrate the new wrapper.

**Comment by caspertone2003** [comment]
confirmed, it is good.
TKS
