### ISSUE TITLE
Borderless Gaming 10.0-rc.1 Latest Version

### ISSUE THREAD

**Issue by rasbayri** [portapps/portapps#350]
### Request guidelines

- [X] I've read the [request guidelines](https://portapps.io/doc/request-app/)

### I've checked that that ...

- [X] ... license allows distribution/repackaging of the software
- [X] ... this is not an abdandonware

### Name

Borderless Gaming

### Description

@crazy-max Hi, sorry to disturb you, is it possible for you to do the latest version? 
Link: https://github.com/Codeusa/Borderless-Gaming/releases/tag/10.0-rc.1

### Website

https://github.com/Codeusa/Borderless-Gaming/

### License

OSS GNU General Public License v2.0

**Comment by crazy-max** [comment]
https://github.com/portapps/borderless-gaming-portable/ is not maintained anymore but feel free to fork and make your own changes
