### ISSUE TITLE
Add a desktop client to access google mail - and perhaps other google services

### ISSUE THREAD

**Issue by caspertone2003** [portapps/portapps#36]
@crazy-max 

Having a portable app, a local application, to read gmail would be useful under certain environments.
One of the most interesting characteristics that the application should have is to allow simulteneous isolated email accounts...

As example, the closest idea I found is wundermail. https://wundermail.app/pricing/
This is closed source, propietary, fremium, only Windows.

I found several potential candidates/approaches, but the number of them seems vast; some are just examples as contraints made them probably not usable for this purpose.

a) GMDesk
https://robertnyman.com/gmdesk/
Seems free. Based on Adobe Flash/Air / Source not publicly available / No info on license

b) Destop app generators, such as Wavebox
https://wavebox.io/
Wavebox allows to "desktopize" web based aplications. Fremium. Source https://github.com/wavebox/waveboxapp
macOS, Windows & Linux
MPL 2.0
Based on electron etc.
It is not a gmail desktop app but a generator of deskop apps....

c) Inboxer
https://github.com/jmarino/inboxer
Available as appimage can not be run freely under W10 (see https://discourse.appimage.org/t/run-appimage-on-windows/177) 

d) several electron based or alike for other SO.

d) IDEAL
- I am still searching for  something like GMDesktop but that would not need Air or similar elements not off the (windows) self, multiple OS, open source, etc.

Will extend the list as I progress with my search

Alternatively, having a dockerized Wundermail running on Docker™ Toolbox portable would be a nice solution.... but I am unsure if dockeriring Wundermail would be not legal/legit.

Might be it would be Franz™ portable the tool I ask for?

Thanks
CT

**Comment by crazy-max** [comment]
Hi @caspertone2003,

The best place to discuss this would be on [our subreddit](https://www.reddit.com/r/Portapps). Can you create a post there ? Thanks.
