### ISSUE TITLE
Distribute a compiled go binary 'portapp launcher' file

### ISSUE THREAD

**Issue by pa-0** [portapps/portapps#366]
### Request guidelines

- [X] I've read the [request guidelines](https://portapps.io/doc/request-app/)

### I've checked that that ...

- [X] ... license allows distribution/repackaging of the software
- [X] ... this is not an abdandonware

### Name

Go

### Description

In the spirit of app-portability, it would be great if portable apps could be loaded onto a USB along with a companion go binary file that would allow running each portapp as the instructions describe without having to install go as a prerequisite.

### Website

golang.com?

### License

OSS

**Comment by EmberHeartshine** [comment]
I may not be totally familiar with this ecosystem, but I haven't had to install Go on any of my machines that have PortApps on them.

**Comment by crazy-max** [comment]
Seems to be a duplicated of https://github.com/portapps/portapps/issues/37
