### ISSUE TITLE
Imo Messenger

### ISSUE THREAD

**Issue by Cyberavater** [portapps/portapps#38]
> Please follow this guide to file a proper request report: https://portapps.io/doc/request-app/

* Name: Imo Messenger
* Description: Imo Messenger for Windows is a popular online instant messaging cellphone app that enables you to chat with your friends, make free video calls, exchange images and photos. Imo Messenger for PC is a desktop version of messaging application that enables you to exchange messages from your desktop or laptop computer. That makes typing much easier and convenient than on a cellphone. The user interface of Imo for PC application is very clean and easy to use but it is also very basic, compared to the cell-phone app. 
* Website: https://imo.im/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Freeware
* Comment (anything else which might help) :

**Comment by crazy-max** [comment]
According to their [TOS](https://imo.im/policies/terms_of_service), it's not allowed to redistribute their product.
