### ISSUE TITLE
f.lux

### ISSUE THREAD

**Issue by seiferflo** [portapps/portapps#39]
* Name : f.lux
* Description : f.lux is a simple and easy to use application developed in order to provide you with the means of automatically adapting your desktop brightness and colors to the night / day lighting conditions. It's even possible that you're staying up too late because of your computer. You could use f.lux because it makes you sleep better, or you could just use it just because it makes your computer look better. 
* Website : https://justgetflux.com/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Free on Windows, for personal use
* Comment (anything else which might help) : 
Folder created in AppData\Local\FluxSoftware
Keys created HKEY_CURRENT_USER\Software\Michael Herf
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Flux
App needs to be able to start at logon in the background, with only icon in the notification bar

Thanks in advance

**Comment by crazy-max** [comment]
According to their [EULA](https://justgetflux.com/news/pages/eula/), it's not allowed to redistribute their product.
