### ISSUE TITLE
Keybase

### ISSUE THREAD

**Issue by chioubaca** [portapps/portapps#4]
Is it possible for you to add Keybase to your amazing collection of apps ?

* Name : Keybase
* Description : Keybase is a messaging and file-sharing app for mobile phones and computers that is fully end-to-end encrypted. 
* Website : https://keybase.io/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : New BSD (3 Clause) License
* Comment (anything else which might help) : 

Ps : thanks a lot for all your work :)

**Comment by crazy-max** [comment]
According to their [terms](https://keybase.io/docs/terms), Keybase is not allowed to be repackaged and distributed.
