### ISSUE TITLE
Wire Messenger

### ISSUE THREAD

**Issue by pcguy01** [portapps/portapps#41]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Wire Messenger (client for Windows)
* Description : Wire is an encrypted communications client for Windows that aims to be truly secure and privacy-friendly. It transmits text messages and files and can make voice and video calls and be used for video conferences. Many employees working for Wire previously worked for Skype.
* Website : https://wire.com/en/products/personal-secure-messenger/
and https://github.com/wireapp/wire
* License (e.g. Freeware, OSS, GPL, MIT, etc) : GPLv3
* Comment (anything else which might help) : Wire is the most extensively publicly audited collaboration software on the market. Wire's source code is 100% open source for anyone to review.

**Comment by crazy-max** [comment]
@pcguy01 Wire is now available : https://portapps.io/app/wire-portable/
Again thanks for your donation and your support!
