### ISSUE TITLE
Navicat Premium

### ISSUE THREAD

**Issue by yetangye** [portapps/portapps#43]
* Name : Navicat Premium
* Description : Navicat Premium
* Website : https://www.navicat.com/en/products/navicat-premium
* License (e.g. Freeware, OSS, GPL, MIT, etc) : 
* Comment (anything else which might help) :

**Comment by crazy-max** [comment]
According to their [Legal Statement](https://www.navicat.com/en/legalstatement), it's not allowed to use their brand and redistribute their products.
