### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by yetangye** [portapps/portapps#44]
* Name : Android Studio
* Description : Android Studio
* Website : https://developer.android.com/studio
* License (e.g. Freeware, OSS, GPL, MIT, etc) : 
* Comment (anything else which might help) : 
When run Android Studio the first time, the folders below will be create:
%USERPROFILE%\.gradle                
%USERPROFILE%\.m2                    
%USERPROFILE%\.android               
%LOCALAPPDATA%\Android               
%USERPROFILE%\.AndroidStudio3.3      
%USERPROFILE%\.AndroidStudio3.4      

I hope the folders above can be portable, not belongs to the current user.

**Comment by crazy-max** [comment]
@pcguy01 Android Studio is now available : https://portapps.io/app/android-studio-portable/

**Comment by yetangye** [comment]
Thanks for your great works!
