### ISSUE TITLE
App request: Adobe XD

### ISSUE THREAD

**Issue by yetangye** [portapps/portapps#45]
* Name : Adobe XD
* Description : Wireframe, design, prototype, present, and share amazing experiences for web, mobile, voice, and more — all in one app. XD is made for designers, creative teams, and organizations that need to design at scale. It’s everything you need to work more efficiently, collaborate effortlessly, and create and manage your design system.
* Website : https://www.adobe.com/products/xd.html
* License (e.g. Freeware, OSS, GPL, MIT, etc) : 
* Comment (anything else which might help) :

**Comment by crazy-max** [comment]
Repackaging Adobe Acrobat and distributing is illegal.
