### ISSUE TITLE
Exodus

### ISSUE THREAD

**Issue by discoli** [portapps/portapps#48]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : exodus
* Description : an electron crypto wallet
* Website : exodus.io
* License (e.g. Freeware, OSS, GPL, MIT, etc) : not sure
* Comment (anything else which might help) : seems to just need changing the userDir to something in the same directory

**Comment by crazy-max** [comment]
Ok after checking the process seems pretty straitforward as others Electron apps. Keep you in touch.

**Comment by discoli** [comment]
Awesome, thank you very much 😄

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by crazy-max** [comment]
Also I have to contact Exodus' developers about their licensing strategy before making a portapp.

**Comment by crazy-max** [comment]
@discoli

> Hi CrazyMax,
> 
> Thank you for writing to us about this.
> 
> I need to clarify your question about the license with the right people on my team, but I'd like to address the request of your users.
> 
> We have been approached by users who wanted to make the app portable or run it from live media. Due to security and usability issues, we don't condone or recommend doing this.
> 
> Please, let me know if this helps. Let's keep in touch.
> 
> Best,
> Gordon

**Comment by discoli** [comment]
@crazy-max 

I hope that he is able to get back to you regarding the licensing.

Regarding the usability and security I'd like to argue that it is more secure to have it installed to another location, for example in my use case I would install it to an encrypted USB stick so I can carry it from computer to computer.

And regarding usability from what I can tell it only accesses the userDir.


I'm not sure what their reasons for not having a portable version is, I hope you do see where I am coming from and if the license is right are able to create one, many users would love and use this:)

**Comment by crazy-max** [comment]
@discoli 

> Thank you for letting me know about this, CrazyMax.
> 
> I've spoken to my teammates, and we would like to ask you to hold back on creating a Portapps release of Exodus. Since we provide wallet software that people use to manage their funds, we take security extremely seriously, and we want to limit alternative distributions of Exodus being available in order to protect our customers and limit any confusion about where to get the official software that has been audited for security and is fully supported by our team of engineers.
> 
> We salute your efforts, it's awesome that you're giving people flexibility and convenience. However, for the reasons mentioned above, we would prefer to create a fully supported portable version ourselves if we see a high enough demand for this. So far, this has been a niche request from a small number of people. Portapps exists to service this niche, so if the circumstances were different, it would have been ideal to let you handle this. I hope you understand our reasoning.
> 
> In terms of a legal backdrop, you can check out our Terms of Use if interested:
> https://www.exodus.io/legal/exodus-tos-41053311-v10.pdf
> 
> Please, let me know if you have any follow-up questions.
> 
> Best,
> Gordon

Following this statement, I will not provide a portapp for Exodus unfortunately.
