### ISSUE TITLE
Brave crash

### ISSUE THREAD

**Issue by justmwa** [portapps/portapps#5]
Hello,
both Brave 0.25 x32 or x64 builds fail to start on Win10Pro on a network drive:
NFO : 2018/11/07 13:54:40.121244 main.go:51: --------
INFO : 2018/11/07 13:54:40.198243 main.go:52: Starting Brave...
INFO : 2018/11/07 13:54:40.198243 main.go:53: Current path: M:\portapps\brave-portable
INFO : 2018/11/07 13:54:40.199244 sys.go:190: Create folder M:\portapps\brave-portable\data...
INFO : 2018/11/07 13:54:40.205246 electron.go:10: Lookup app folder in: M:\portapps\brave-portable\app
INFO : 2018/11/07 13:54:40.208244 electron.go:14: Electron app folder found: app-0.25.2
INFO : 2018/11/07 13:54:40.209247 exec.go:29: Process: M:\portapps\brave-portable\app\Brave.exe
INFO : 2018/11/07 13:54:40.210247 exec.go:30: Args:  
INFO : 2018/11/07 13:54:40.210247 exec.go:31: Working dir: M:\portapps\brave-portable\app\app-0.25.2
INFO : 2018/11/07 13:54:40.211248 exec.go:32: Data path: M:\portapps\brave-portable\data
INFO : 2018/11/07 13:54:40.212247 exec.go:34: Launch Brave...
INFO : 2018/11/07 13:54:40.212247 exec.go:41: Exec M:\portapps\brave-portable\app\Brave.exe  
[10132:17088:1107/135442.851:ERROR:browser_gpu_channel_host_factory.cc(132)] Failed to launch GPU process.
Crash reporting enabled
[10132:17088:1107/135451.550:ERROR:browser_gpu_channel_host_factory.cc(132)] Failed to launch GPU process.
Window crashed. Reloading...
[10132:21848:1107/135451.582:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.
Window crashed. Reloading...
Window crashed. Reloading...
Window crashed. Reloading...
Window crashed. Reloading...
Window crashed. Reloading...
Window crashed. Reloading...
(node:10132) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 notification-response listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 notification-response listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:262:19)
    at EventEmitter.addListener (events.js:279:10)
    at WebContents.win.webContents.on (M:\portapps\brave-portable\app\app-0.25.2\resources\app.asar\app\browser\windows.js:350:19)
    at emitOne (events.js:96:13)
    at WebContents.emit (events.js:191:7)
Window crashed. Reloading...
Window crashed. Reloading...

hogging CPU until I kill it.
Fresh install !

**Comment by crazy-max** [comment]
@justmwa Next time, open an issue on the right repository please : https://github.com/crazy-max/brave-portable

**Comment by justmwa** [comment]
Thanks for the reply. 
You're right, as much as the "won't run on a network drive" is a Brave issue and not a general portapps one :) 


De: "CrazyMax" <notifications@github.com> 
À: "portapps/portapps" <portapps@noreply.github.com> 
Cc: "justmwa" <dev@1e.ca>, "Mention" <mention@noreply.github.com> 
Envoyé: Jeudi 8 Novembre 2018 11:41:18 
Objet: Re: [portapps/portapps] Brave crash (#5) 



[ https://github.com/justmwa | @justmwa ] Next time, open an issue on the right repository please : [ https://github.com/crazy-max/brave-portable | https://github.com/crazy-max/brave-portable ]
