### ISSUE TITLE
RealMeteo

### ISSUE THREAD

**Issue by shop2007** [portapps/portapps#53]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : RealM;eteo
* Description :   forecast metep aotmatic browser
* Website :  https://www.realmeteo.com/public/RealMeteo5-NEWS-RealMeteo_Portable_ENG.asp
* License (e.g. Freeware, OSS, GPL, MIT, etc) :  freeware
* Comment (anything else which might help) :  contact register@realmeteo.com

**Comment by crazy-max** [comment]
Sorry but based on [Alexa rank](https://www.alexa.com/siteinfo/realmeteo.com) this application does not have sufficient visibility.
