### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by Velgus** [portapps/portapps#54]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Fork
* Description : A fast and friendly git client for Mac and Windows
* Website : https://git-fork.com/windows
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Freeware (https://git-fork.com/license)
* Comment (anything else which might help) : It's hard-coded to store several files in %LOCALAPPDATA%\Fork

**Comment by crazy-max** [comment]
According to their [license](https://git-fork.com/license), Fork is not allowed to be repackaged and distributed.

>  You will not, and will not permit others to:
> 
> 1) reverse engineer, decompile, disassemble, derive the source code of, modify, or create derivative works from this Software, or
> 
> 2) copy, distribute, publicly display, or publicly perform content contained in this Software other than as expressly authorized by this Agreement. 

But I'll contact the developers for more information.

**Comment by crazy-max** [comment]
Response form Fork Support :

> Hi,
> 
> As you've seen (https://github.com/portapps/portapps/issues/54), Fork does not allow modification and redistribution.
> 
> There are many reasons for that:
> 
> - Security.
> - Security. Fork has access to users **source code** and allowing to distribute binaries under same brand somewhere else is not possible.
> - Fork and its installer are signed with code-sign certificate. Not sure how you was planning to handle that.
> - It took me a lot of efforts to become green on VirusTotal. The modified version will certainly be marked as a not trusted there and I don’t want to have risks with that.
> - Automatic updates. Fork for Windows is a bit older than 1 year and During that period we released 37 major updates (and about 10 minor ones). Having all the users on the latest version really makes the development easier.
> - Fork keeps it’s settings and git instance in %localappdata%
> - Fork is not mature enough to become standalone yet. When it is, I’ll be happy to help with a portable version, or publish it myself.
> 
> Regards,
> 
> Dan
