### ISSUE TITLE
Station

### ISSUE THREAD

**Issue by fuzuyx** [portapps/portapps#56]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Station
* Description : Station is the first smart browser for busy people. A single place for all of your web applications.
* Website : https://getstation.com
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Can't find
* Comment (anything else which might help) : It would be great having portable apps that save site data

**Comment by crazy-max** [comment]
According to their [TOS](https://community.getstation.com/tos), it's not allowed to redistribute their product.
