### ISSUE TITLE
LaTeX Environment - MiKTeX + TeXStudio + TeXMaker

### ISSUE THREAD

**Issue by RoyiAvital** [portapps/portapps#6]
Basically we want a Portable LaTeX Enviornment in Windows based on MiKTeX, TeXStudio and TeXMaker.  
I will describe each according to the format.

## MiKTeX
* Name :  [MiKTeX](https://miktex.org/)
* Description : MiKTeX (pronounced mick-tech) is an up-to-date implementation of TeX/LaTeX and related programs.  
TeX is a typesetting system written by Donald Ervin Knuth who says that it is intended for the creation of beautiful books - and especially for books that contain a lot of mathematics.
* Website : https://miktex.org/ and https://github.com/MiKTeX/miktex
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Free Software Foundation
* Comment (anything else which might help) :  This is a service which should run in the background. Have a look on [PortableApps MiKTeX](https://portableapps.com/node/53801) and [PortableApps MiKTeX Launcher](https://portableapps.com/node/36247).

## TeXStudio
* Name :  [TeXStudio](https://www.texstudio.org/)
* Description : TeXstudio is an integrated writing environment for creating LaTeX documents. Our goal is to make writing LaTeX as easy and comfortable as possible. Therefore TeXstudio has numerous features like syntax-highlighting, integrated viewer, reference checking and various assistants. For more details see the features.
TeXstudio is open source and is available for all major operating systems.
* Website : https://www.texstudio.org/ and https://github.com/texstudio-org/texstudio/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : GNU GENERAL PUBLIC LICENSE Version 3
* Comment (anything else which might help) :  As a reference one could have a look at [PortableApps TeXStudio](https://portableapps.com/node/53350).

## TeXMaker
* Name :  [TeXMaker](http://www.xm1math.net/texmaker/)
* Description : Texmaker is a free, modern and cross-platform LaTeX editor for linux, macosx and windows systems that integrates many tools needed to develop documents with LaTeX, in just one application.
Texmaker includes unicode support, spell checking, auto-completion, code folding and a built-in pdf viewer with synctex support and continuous view mode.
Texmaker is easy to use and to configure.
Texmaker is released under the GPL license .
TeXstudio is open source and is available for all major operating systems.
* Website : http://www.xm1math.net/texmaker/ and https://github.com/texstudio-org/texstudio/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : GNU GENERAL PUBLIC LICENSE Version 2
* Comment (anything else which might help) :  There are old build of PortableApps for TeXMaker 4.x.

**Comment by Anio-pke** [comment]
too!

**Comment by JustAPhrog** [comment]
It will be good to see it portable :simple_smile:

**Comment by crazy-max** [comment]
@RoyiAvital Portapps does not cover _mixed apps_.

**Comment by RoyiAvital** [comment]
I don't think it should be a mixed apps.
I think you should add "Framework Apps".

Applications which give service to many other applications.
MiKTeX is such an application and a different application in the package can be TeXStudio.
