### ISSUE TITLE
Ferdi

### ISSUE THREAD

**Issue by Makazzz** [portapps/portapps#61]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Ferdi
* Description : Hard-fork of Franz, adding awesome features and removing unwanted features.
* Website : https://github.com/getferdi/ferdi
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Apache 2.0
* Comment (anything else which might help) : I think it should be easy because Franz is already in portapps format.

**Comment by crazy-max** [comment]
@Makazzz Going to work on this. Keep you in touch.

**Comment by crazy-max** [comment]
Available: https://portapps.io/app/ferdi-portable/
