### ISSUE TITLE
InnoSetup

### ISSUE THREAD

**Issue by crazy-max** [portapps/portapps#64]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : InnoSetup
* Description : A free installer for Windows programs
* Website : http://www.jrsoftware.org/isinfo.php
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Freeware
* Comment (anything else which might help) :

**Comment by RoyiAvital** [comment]
I'd add NSIS as well.

**Comment by crazy-max** [comment]
@RoyiAvital Can you create a new app request for NSIS please?

**Comment by crazy-max** [comment]
Now available : https://portapps.io/app/innosetup-portable/
