### ISSUE TITLE
Cisco AnyConnect VPN Client

### ISSUE THREAD

**Issue by skyfire000** [portapps/portapps#66]
Name : Cisco AnyConnect VPN
    Description : A VPN Client
    Website : https://www.cisco.com/c/en/us/products/security/anyconnect-secure-mobility-client/index.html
    License (e.g. Freeware, OSS, GPL, MIT, etc) : biz
    Comment (anything else which might help) :

**Comment by crazy-max** [comment]
According to their [EULA](https://www.cisco.com/c/dam/en_us/about/doing_business/legal/seula/DOC-1.pdf), it's not allowed to redistribute their product.
