### ISSUE TITLE
ungoogled-chromium

### ISSUE THREAD

**Issue by zenofkarma** [portapps/portapps#67]
* Name : Ungoogled-chromium
* Description : Browser
* Website : https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : BSD-3-clause
* Comment (anything else which might help) : Thank you very much.

**Comment by meiuwa** [comment]
Please put this on top priority...

**Comment by crazy-max** [comment]
I have started to work on this. Keep you in touch.

**Comment by crazy-max** [comment]
Now available : https://portapps.io/app/ungoogled-chromium-portable/
