### ISSUE TITLE
Picasa from Google

### ISSUE THREAD

**Issue by vvv-easy** [portapps/portapps#69]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Picasa from Google
* Description : Who doesn't know Picasa? A photo organizer with face recognition and more.
* Website : https://picasa.google.com/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Abandoned freeware
* Comment (anything else which might help) :
A several years ago Google has abandoned Picasa solution for Google Photos but even today is a very good software. This has an great advantage, you only have to make it portable once
Today, it is not disponible in Google site but you can donwload it in several places for instance in **snapfiles**:
 [https://www.snapfiles.com/get/picasa.html](url)
http://files.snapfiles.com/directdl/picasa39-setup.exe

Thank you for your work.

**Comment by vvv-easy** [comment]
One comment more: I have downloaded the file and extracting the program I'm able to use it portable but it write to:
**%APPDATA%\Local\Google\Picasa2
%APPDATA%\Local\Google\Picasa2Albums**
and in the **Registry**

**Comment by crazy-max** [comment]
@vvv-easy As stipulated on [Request app page](https://portapps.io/doc/request-app/), Abandonware will not be processed.
