### ISSUE TITLE
Discord Canary

### ISSUE THREAD

**Issue by GameMaster2030** [portapps/portapps#7]
* Name : Discord Canary
* Description : Canary version of discord
* Website : [discordapp.com](https://discordapp.com)
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Freeware
* Comment (anything else which might help) : Download link: [Here](https://discordapp.com/api/download/canary?platform=win)

**Comment by crazy-max** [comment]
@GameMaster2030 [Discord PTB](https://portapps.github.io/app/discord-ptb-portable/) is already available. If you want a Canary version, feel free to fork the project and bring the required modifications :slightly_smiling_face:
