### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by Lettly** [portapps/portapps#70]
• Name : Telegram
• Description : Telegram is a cloud-based instant messaging and voice over IP service 
• Website : https://github.com/telegramdesktop/tdesktop
• License (e.g. Freeware, OSS, GPL, MIT, etc) : GNU 3
• Comment (anything else which might help) : since you have already worked on WhatsApp, I hope this is no longer difficult

**Comment by zenofkarma** [comment]
Hi Lettly,

There is an official portable version of Telegram on their website or Github. I used it for a long time with no problem.  You can check it at the following link:
https://github.com/telegramdesktop/tdesktop/releases
![Capture123](https://user-images.githubusercontent.com/28623914/65938949-a480d780-e44e-11e9-83b5-191a596eb2d9.PNG)

**Comment by crazy-max** [comment]
@Lettly As @zenofkarma said, Telegram is already available as a portable app.
