### ISSUE TITLE
Signal

### ISSUE THREAD

**Issue by seiferflo** [portapps/portapps#77]
* Name : **Signal**
* Description : **Encrypted messaging service**
* Website : **https://signal.org/download/**
* License (e.g. Freeware, OSS, GPL, MIT, etc) : **GPLv3**
* Comment (anything else which might help) : **Git: https://github.com/signalapp, Desktop app for Windows, Mac OS, Debian based Linux**

No-one has done a portable app so far... Thanks in a lot in advance.

**Comment by crazy-max** [comment]
I have to contact Signal developers about their licensing strategy before making a portapp.

**Comment by seiferflo** [comment]
Ho @crazy-max, have you got any update by any chance?

**Comment by crazy-max** [comment]
@seiferflo No response from them unfortunately. You can try to contact them on your own if you like.

**Comment by MikeBlueberry** [comment]
Signal devs don't seem to care about a portable version.  Use [Session](https://getsession.org/) instead.

**Comment by seiferflo** [comment]
yes papa, thank you @crazy-max for doing Signal !

**Comment by crazy-max** [comment]
@seiferflo Oh didn't see #171 duplicates this one. Closing then :)
