### ISSUE TITLE
Instagram App

### ISSUE THREAD

**Issue by Blorx** [portapps/portapps#79]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Instagram
* Description : A simple, fun & creative way to capture, edit & share photos, videos & messages with friends & family.
* Website : NA- Google Play/App Store app
* License (e.g. Freeware, OSS, GPL, MIT, etc) : 
* Comment (anything else which might help) : With texting.

**Comment by crazy-max** [comment]
There is no desktop app for Instagram

**Comment by Blorx** [comment]
There is the windows 10 app store.

**Comment by crazy-max** [comment]
@Blorx Windows Apps are not (currently) supported.
