### ISSUE TITLE
Cryptomator

### ISSUE THREAD

**Issue by pooryay21** [portapps/portapps#85]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : Cryptomator
* Description : Free client-side encryption for your cloud (and local) files. Open source software: No backdoors, no registration.
* Website : https://cryptomator.org/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : GPLv3
* Comment (anything else which might help) : Functions akin to Truecrypt/Veracrypt where you store files within a mounted encrypted file system container, so that may be tough to work around for portability. I believe it's using EncFS for encryption, and I've found the speed and ease of use to be 5 star quality.

**Comment by crazy-max** [comment]
@pooryay21 Available: https://portapps.io/app/cryptomator-portable/
