### ISSUE TITLE
GitHub desktop

### ISSUE THREAD

**Issue by sunk818** [portapps/portapps#87]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : GitHub Desktop
* Description : Git client for GitHub
* Website : https://desktop.github.com/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : ?
* Comment (anything else which might help) :

They have an update mechanism within the app itself, so I don't know how easy it will be to update or not. Firefox Portable is super cool because even if you update from the app itself, it just updates the portable directory.

**Comment by crazy-max** [comment]
According to their [EULA](https://desktop.github.com/eula/), it's not allowed to redistribute their product.

**Comment by sekedus** [comment]
> According to their [EULA](https://desktop.github.com/eula/), it's not allowed to redistribute their product.

See [this post](https://portableapps.com/comment/253340#comment-253340)
