### ISSUE TITLE
Way to disable log

### ISSUE THREAD

**Issue by fhoshino** [portapps/portapps#92]
Is there a flag for the config file to disable the creation of the log and the log folder?

**Comment by crazy-max** [comment]
`disable_log` config is available for apps using Portapps 2.0.0 or higher

**Comment by fhoshino** [comment]
Log file is still created and not cleanup even with the following config on 2.0.2
```app:
  cleanup: true
  disable_log: true```

**Comment by crazy-max** [comment]
@fhoshino It's not available through `app` section but `common`. See [Configuration page](https://portapps.io/doc/configuration/) for more info.
