### ISSUE TITLE
Move config file args after hardcoded args?

### ISSUE THREAD

**Issue by iBenMoore** [portapps/portapps#95]
### Behaviour
When including custom args in a yml config file, the "config file" args are included in the command line that gets called before the "hardcoded" args.  For many apps this likely wouldn't be an issue, but with dBeaver if you're attempting to include -vmargs any args following the vmargs are considered vmargs, and so the -data and -vm hardcoded args aren't processed correctly.  I was looking to include custom -vmargs in the yml file instead of the app directory dbeaver.ini file so when updating the app to a newer version the custom args would not get overwritten.

#### Steps to reproduce this issue

1.  Include -vmargs args in a dbeaver-portable.yml file
2.  Start dbeaver-portable.exe, and notice that the 'portable' data and vm hardcoded args aren't getting applied correctly.
3.  Review the dbeaver-portable.log and notice the command line that is built and the order the args are included.

#### Expected behaviour

hardcoded vmargs included in the called command line before the config file args

#### Actual behaviour

config file args are included in the called command line before the hardcoded args

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : 6.3.1-23

**Operating system (ex. Windows 10 Pro 64 bits)** :Windows 10 x64

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

**Comment by crazy-max** [comment]
@iBenMoore Can you post your `dbeaver-portable.log` file please?

**Comment by crazy-max** [comment]
Closed due to inactivity
