### ISSUE TITLE
MySQL Workbench

### ISSUE THREAD

**Issue by ZRamadhan** [portapps/portapps#97]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : MySQL Workbench
* Description : MySQL Workbench is a unified visual tool for database architects, developers, and DBAs. MySQL Workbench provides data modeling, SQL development, and comprehensive administration tools for server configuration, user administration, backup, and much more. MySQL Workbench is available on Windows, Linux and Mac OS X
* Website : https://www.mysql.com/products/workbench/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : MIT
* Comment (anything else which might help) : I wanted this application to be portable, if available for me and my friend usage for studying and web making.

**Comment by crazy-max** [comment]
@ZRamadhan According to their [legal notices](https://dev.mysql.com/doc/workbench/en/wb-preface.html), it's not allowed to redistribute their product.
