### ISSUE TITLE
Anaconda Portable

### ISSUE THREAD

**Issue by odm7341** [portapps/portapps#98]
* Name : Anaconda 
* Description : A machine learning platform for python
* Website : https://www.anaconda.com/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : BSD
* Comment (anything else which might help) : A portable edition of this app would be extremely helpful for students like myself that work in their college's labs and cannot install software on those computers.

**Comment by crazy-max** [comment]
@odm7341 According to their [EULA](https://docs.anaconda.com/anaconda/eula/), we need a specific prior written permission to use their brand. Can you ask them?
